apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: node-ssh-tunnel-credentials
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: node-ssh-tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: secret/data/cloudflare/node-ssh-tunnel-credentials
        property: credentials.json
