# Avahi daemon configuration for Samba mDNS advertisement
# Managed by Ansible (ansible/playbooks/samba.yaml)

[server]
host-name=NAS
use-ipv4=yes
use-ipv6=no
allow-interfaces=ens1,ens2
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=no

[publish]
publish-hinfo=no
publish-workstation=no
publish-aaaa-on-ipv4=no

[reflector]
enable-reflector=no

[rlimits]
