apiVersion: v1
kind: Service
metadata:
  name: mcp-lostfilm
  namespace: mcp-lostfilm
spec:
  selector:
    app.kubernetes.io/name: mcp-lostfilm
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
