apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap-secrets
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: lldap-secrets
    creationPolicy: Owner
  data:
    - secretKey: LLDAP_LDAP_USER_PASS
      remoteRef:
        key: secret/data/lldap
        property: LLDAP_LDAP_USER_PASS
    - secretKey: LLDAP_JWT_SECRET
      remoteRef:
        key: secret/data/lldap
        property: LLDAP_JWT_SECRET
