apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zfs-localpv
  resources:
    requests:
      storage: 500Mi
