apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: security
  labels:
    app.kubernetes.io/name: lldap
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lldap
  ports:
    - name: ldap
      port: 3890
      targetPort: ldap
      protocol: TCP
    - name: http
      port: 17170
      targetPort: http
      protocol: TCP
