[supervisord]
nodaemon=true
user=dev
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:dockerd]
command=bash -c "mkdir --parents /home/dev/.docker/run && exec dockerd-rootless.sh"
user=dev
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=XDG_RUNTIME_DIR="/home/dev/.docker/run",HOME="/home/dev"
priority=10

[program:vscode]
command=code serve-web
    --host=0.0.0.0
    --port=8080
    --without-connection-token
    --accept-server-license-terms
    --server-data-dir=/home/dev/.vscode-server
    --telemetry-level=off
user=dev
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME="/home/dev"
priority=20
