FROM alpine:3.23

RUN apk add --no-cache samba-server samba-common-tools

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 445/tcp

ENTRYPOINT ["/entrypoint.sh"]
CMD ["smbd", "--foreground", "--no-process-group"]
