apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        key: secret/data/authelia
        property: ARGOCD_CLIENT_SECRET
    - secretKey: ARGOCD_CLIENT_SECRET_HASHED
      remoteRef:
        key: secret/data/authelia
        property: ARGOCD_CLIENT_SECRET_HASHED
    - secretKey: GRAFANA_CLIENT_SECRET_HASHED
      remoteRef:
        key: secret/data/authelia
        property: GRAFANA_CLIENT_SECRET_HASHED
    - secretKey: OPENBAO_CLIENT_SECRET_HASHED
      remoteRef:
        key: secret/data/authelia
        property: OPENBAO_CLIENT_SECRET_HASHED
    - secretKey: CLAUDE_WORKSPACE_CLIENT_SECRET
      remoteRef:
        key: secret/data/authelia
        property: CLAUDE_WORKSPACE_CLIENT_SECRET
    - secretKey: GRAFANA_CLIENT_SECRET
      remoteRef:
        key: secret/data/authelia
        property: GRAFANA_CLIENT_SECRET
    - secretKey: JELLYFIN_CLIENT_SECRET
      remoteRef:
        key: secret/data/authelia
        property: JELLYFIN_CLIENT_SECRET
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/data/authelia
        property: JWT_SECRET
    - secretKey: OIDC_HMAC_SECRET
      remoteRef:
        key: secret/data/authelia
        property: OIDC_HMAC_SECRET
    - secretKey: OIDC_PRIVATE_KEY
      remoteRef:
        key: secret/data/authelia
        property: OIDC_PRIVATE_KEY
    - secretKey: OPENBAO_CLIENT_SECRET
      remoteRef:
        key: secret/data/authelia
        property: OPENBAO_CLIENT_SECRET
    - secretKey: SESSION_SECRET
      remoteRef:
        key: secret/data/authelia
        property: SESSION_SECRET
    - secretKey: STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: secret/data/authelia
        property: STORAGE_ENCRYPTION_KEY
    - secretKey: OPENCLAW_CLIENT_SECRET
      remoteRef:
        key: secret/data/authelia
        property: OPENCLAW_CLIENT_SECRET
    - secretKey: USER_PASSWORD
      remoteRef:
        key: secret/data/authelia
        property: USER_PASSWORD
